version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - wsl_v5
    - nlreturn
    - gocritic
    - errcheck
    - staticcheck
    - gocyclo
    - revive
    - goconst
    - unparam
    - ineffassign
    - unused
    - misspell

  settings:
    nlreturn:
      block-size: 3
    gocritic:
      enable-all: true

formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt