version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - wsl_v5
    - nlreturn
    - gocritic
    - errcheck
    - staticcheck
    - gocyclo
    - revive
    - goconst
    - unparam
    - ineffassign
    - unused
    - misspell
  settings:
    nlreturn:
      block-size: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - whyNoLint
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes: ["code"]