sonar.projectKey=dark7lord_go-project-244
sonar.organization=dark7lord

sonar.sources=.
sonar.exclusions=**/*_test.go   # исключаем тесты из основного анализа
sonar.tests=.                   # но указываем, где искать тесты (те же файлы, но они будут обработаны как тесты)
sonar.test.inclusions=**/*_test.go

sonar.host.url=https://sonarcloud.io
sonar.go.coverage.reportPaths=coverage.out